---
apiVersion: v1
kind: Pod
metadata:
  name: vpp-app2
  labels:
    name: vpp-app2
  namespace: vpp
  annotations:
    k8s.v1.cni.cncf.io/networks: userspace-vpp-net-1
    userspace/mappedDir: /var/lib/cni/usrspcni/
spec:
  nodeSelector:
    kubernetes.io/hostname: kind-control-plane # replace this with your hostname
  hostname: vpp-app2
  subdomain: vpp
  containers:
  - image: ligato/vpp-base:23.02 #imagename
    imagePullPolicy: IfNotPresent
    name: vpp-app1
    volumeMounts:
    - name: podinfo
      mountPath: /etc/podinfo
    - name: vpp-startup-config
      mountPath: /etc/vpp/
    - name: hugepage
      mountPath: /hugepages
    - name: shared-dir
      mountPath: /var/lib/cni/usrspcni/
    - name: scripts
      mountPath: /vpp/
    resources:
      requests:
        hugepages-2Mi: 1Gi
        memory: "1Gi"
        cpu: "3"
      limits:
        hugepages-2Mi: 1Gi
        memory: "1Gi"
        cpu: "3"
  restartPolicy: Always
  volumes:
    - name: podinfo
      downwardAPI:
        items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations
    - name: vpp-startup-config
      configMap:
        name: vpp-startup-config
    - name: hugepage
      emptyDir:
        medium: HugePages
    - name: shared-dir
      hostPath:
        path: /run/vpp/app2
    - name: scripts
      configMap:
        name: vpp-pod-setup-memif
        defaultMode: 0777
