version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /docker/userspacecni/
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /ci/ovs_test_setup
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /ci/ovs_test_setup/testpmd_image
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /docker/testpmd
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /docker/userspacecni
    schedule:
      interval: daily
