exemptions:
  - checks:
      - pinned-dependencies
    annotations:
      # The CI files should not be pinned
      # because the do not ship with the product.
      - annotation: not-applicable
        paths:
          - ci/*
          - ci/ovs_test_setup/testpmd_image/Dockerfile
          - docker/testpmd/Dockerfile
          - ci/ci.sh
      # other dependencies can be penalized
