---
apiVersion: v1
kind: Pod
metadata:
  name: ovs-app1
  labels:
    name: ovs-app1
  namespace: ovs
  annotations:
    k8s.v1.cni.cncf.io/networks: userspace-ovs-net-1
    userspace/mappedDir: /var/lib/cni/usrspcni/
spec:
  nodeSelector:
    kubernetes.io/hostname: kind-control-plane # replace this with your hostname
  hostname: ovs-app1
  subdomain: ovs
  containers:
  - image: localhost:5000/testpmd #replace this with your docker reg and image name
    imagePullPolicy: IfNotPresent
    name: ovs-app1
    volumeMounts:
    - name: podinfo
      mountPath: /etc/podinfo
    - name: hugepage
      mountPath: /hugepages
    - name: shared-dir
      mountPath: /var/lib/cni/usrspcni/
    - name: vfio
      mountPath: /dev/vfio/
    resources:
      requests:
        hugepages-2Mi: 1Gi
        memory: "500Mi"
        cpu: "5"
      limits:
        hugepages-2Mi: 1Gi
        memory: "500Mi"
        cpu: "5"
#    command: ["/bin/sh"]
#    args: ["-c", "sleep inf"]
  restartPolicy: Always
  volumes:
    - name: podinfo
      downwardAPI:
        items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations
    - name: hugepage
      emptyDir:
        medium: HugePages
    - name: shared-dir
      hostPath:
        path: /run/openvswitch/app1
    - name: vfio
      hostPath:
        path: /dev/vfio/
