apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: userspace-cni-amd64
  namespace: kube-system
  labels:
    tier: node
    app: userspace-cni
spec:
  selector:
    matchLabels:
      app: userspace-cni
  template:
    metadata:
      labels:
        tier: node
        app: userspace-cni
    spec:
      hostNetwork: true
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: userspace-cni-plugin
        image: parthyadav/userspace-cni:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        securityContext:
          privileged: true
        volumeMounts:
        - name: cnibin
          mountPath: /host/opt/cni/bin
      volumes:
        - name: cnibin
          hostPath:
            path: /opt/cni/bin

