apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: userspace-networkobj
spec:
  config: '{
    "cniVersion": "0.3.0",
    "type": "userspace",
    "host": {
      "engine": "ovs-dpdk",
      "iftype": "vhostuser"
    }
  }'
