apiVersion: v1
kind: Pod
metadata:
  name: multi-vhost-example
  annotations:
    k8s.v1.cni.cncf.io/networks: userspace-networkobj, userspace-networkobj
spec:
  containers:
  - name: multi-vhost-example
    image: ubuntu-dpdk
    imagePullPolicy: Never
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /vhu/
      name: socket
    - mountPath: /mnt/huge
      name: hugepage
    resources:
      requests:
        memory: 1Gi
      limits:
        hugepages-1Gi: 1Gi
    command: ["sleep", "infinity"]
  volumes:
  - name: socket
    hostPath:
      path: /var/lib/cni/vhostuser/
  - name: hugepage
    emptyDir:
      medium: HugePages
